
---
title: "About Me"
---

## Background

I'm a 3rd-year student at the University of Münster, developing skills 
in data analysis, business intelligence, and statistical computing.

## Skills & Tools

**Analysis:**

- R for data analysis
- Data cleaning and transformation
- Statistical analysis and interpretation

**Visualization & Reporting:**

- ggplot2 for professional visualizations
- R Markdown for reproducible reports
- Data storytelling for business audiences

**Data Sources:**

- CSV file processing
- Government open data (via APIs)
- Business performance datasets

## Education

- Information Systems at the University of Münster
- Information Systems at the Vancouver Island University

## Contact

Feel free to connect with me:

- Email: [gerrit.wichern@uni-muenster.de](mailto:gerrit.wichern@uni-muenster.de)
- LinkedIn: [Gerrit Wichern](https://www.linkedin.com/in/gerrit-wichern-00748b304/)
- GitHub: [WichernG](https://github.com/WichernG/)

---


[← Back to Home](index.html)
